# Generated by Django 4.1.1 on 2022-09-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('auther', models.TextField(max_length=250)),
                ('type', models.TextField(max_length=254)),
                ('ispn', models.BigIntegerField(max_length=254)),
                ('copies', models.SmallIntegerField(max_length=254)),
                ('issue_date', models.DateField()),
                ('out', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=254)),
                ('department', models.TextField(max_length=254)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('blacklisted', models.BooleanField()),
                ('borrower_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
