# Generated by Django 4.1.1 on 2022-09-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auther',
            field=models.TextField(max_length=56),
        ),
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.SmallIntegerField(max_length=56),
        ),
        migrations.AlterField(
            model_name='book',
            name='ispn',
            field=models.BigIntegerField(max_length=56),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(max_length=56),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.TextField(max_length=56),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='department',
            field=models.TextField(max_length=56),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='name',
            field=models.TextField(max_length=56),
        ),
    ]
