# Generated by Django 4.1.1 on 2022-09-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_auther_alter_book_copies_alter_book_ispn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ispn',
            new_name='isbn',
        ),
    ]
