# Generated by Django 4.1.1 on 2022-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_ispn_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auther',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='book',
            name='issue_date',
            field=models.DateField(help_text='Date format MM-DD-YYYY'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='book',
            name='out',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='department',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='name',
            field=models.CharField(max_length=56),
        ),
    ]
