# Generated by Django 4.1.1 on 2022-10-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_auther_alter_book_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.PositiveSmallIntegerField(max_length=56),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveBigIntegerField(max_length=56),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
