# Generated by Django 4.1.1 on 2022-10-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_copies_alter_book_isbn_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrower_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_borrower', to='books.book'),
        ),
    ]
